name: Deploy to Entry Container Registry

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: create resource folder
        run: |
          mkdir -p ./husky/src/main/resources
      - name: download font archieve for pdf generating
        run: |
          wget --no-check-certificate \
          --http-user=${{ secrets.STATIC_USERNAME }} \
          --http-password=${{ secrets.STATIC_PASSWORD }} \
          https://static.entrydsm.hs.kr/fonts/husky_fonts.zip
        working-directory: ./husky/src/main/resources
      - name: upzip the font archieve
        run: unzip husky_fonts.zip && rm husky_fonts.zip
        working-directory: ./husky/src/main/resources
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: husky
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          tags: "latest"
