name: Java CI with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prepare download fonts
        run: |
          mkdir -p ./src/main/resources/fonts

      - name: download font archieve for pdf generating
        working-directory: ./src/main/resources
        run: |
          wget --no-check-certificate \
          --http-user=${{ secrets.STATIC_USERNAME }} \
          --http-password=${{ secrets.STATIC_PASSWORD }} \
          https://static.entrydsm.hs.kr/fonts/husky_fonts.zip

      - name: upzip the font archieve
        working-directory: ./src/main/resources
        run: |
          unzip husky_fonts.zip -d ./fonts && rm husky_fonts.zip

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
