spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
  jpa:
    generate-ddl: true
  jackson:
    property-naming-strategy: SNAKE_CASE

aws:
  credential:
    access_key_id: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}

auth:
  jwt:
    secret: ${JWT_SECRET_KEY}
    exp:
      access: ${JWT_ACCESS_EXP}
      refresh: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
  maintenance:
    key: ${MAINTENANCE_KEY}
